sudo: false
language: node_js
node_js:
  - 'stable'
script:
  - node render.js >dist/all.pdf
after_script:
  - ls -lh dist/all.pdf
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: dist
